#!/usr/bin/env python

import argparse

import png

# pipwindow

"""Tool to crop/expand an image to a rectangular window.
Come the revolution
this tool will allow the image and the window to be placed arbitrarily
(in particular the window can be bigger than the picture
and/or overlap it only partially) and
the image can be OpenGL style # border/repeat effects
(repeat, mirrored repeat, clamp,
fixed background colour, background colour from source file).
For now this tool only crops.
The window must be no greater than the image in
both x and y.
Coordinates are with (0,0) being the top-left
(as in ImageMagick).
"""


def window(tl, br, inp, out):
    """Place a window onto the image and cut-out the resulting
    rectangle.  The window is an axis aligned rectangle opposite corners
    at *tl* and *br* (each being an (x,y) pair). *inp* specifies the
    input file which should be a PNG image.
    """

    left, top = tl
    right, bottom = br

    r = png.Reader(file=inp)
    x, y, pixels, meta = r.asDirect()

    if top is None:
        top = 0
    if left is None:
        left = 0
    if bottom is None:
        bottom = y
    if right is None:
        right = x

    if not (0 <= left < right <= x):
        raise NotImplementedError()
    if not (0 <= top < bottom <= y):
        raise NotImplementedError()
    # Compute left and right index bounds for each row,
    # given that each row is a flat row of values.
    l = left * meta["planes"]
    r = right * meta["planes"]

    def itercrop():
        """An iterator to perform the crop."""

        for i, row in enumerate(pixels):
            if i < top:
                continue
            if i >= bottom:
                # Same as "raise StopIteration"
                return
            yield row[l:r]

    meta["size"] = (right - left, bottom - top)
    w = png.Writer(**meta)
    w.write(out, itercrop())


def main(argv=None):
    import sys

    if argv is None:
        argv = sys.argv
    argv = argv[1:]

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int)
    parser.add_argument("--left", type=int)
    parser.add_argument("--bottom", type=int)
    parser.add_argument("--right", type=int)
    parser.add_argument(
        "input", nargs="?", default="-", type=png.cli_open, metavar="PNG"
    )

    args = parser.parse_args(argv)

    return window(
        (args.left, args.top),
        (args.right, args.bottom),
        args.input,
        png.binary_stdout(),
    )


if __name__ == "__main__":
    main()
