#!/usr/bin/env python

import sys

# Test that Python 3 is the default Python.
# If this test fails, it is not worth running the remaining tests.
print("Python 3 successful; version is", sys.version, end="\n")
