#!/bin/sh

PATH=${PWD%code*}code:$PATH

# Note basn0g08 includes a gAMA chunk
python -m pngsuite basn0g08 | pripnglsch | grep -q gAMA || exit 9
python -m pngsuite basn0g08 | prichunkpng --delete gAMA - |
  pripnglsch | grep -q gAMA && exit 1
exit 0
