#!/bin/sh

PATH=${PWD%code*}code:$PATH

# Encode a forged PNG using a palette

priforgepng -s 32 -d 3 grl glr rtl | priweavepng - - - |
  pripalpng - | pripnglsch | grep IHDR |
  grep -q 00000020000000200803000000
