#!/bin/sh

PATH=${PWD%code*}code:$PATH

img () {
#                   R     R     R     r     r     r     R     R     R
printf 'P6\n3 3 3\n\1\1\0\2\1\0\3\1\1\2\1\0\3\1\0\1\1\2\3\1\0\1\1\0\2\1\3' |
  pripamtopng -
}

img |
  priweavepng -c 2,1,3 - |
  pripngtopam - |
  tail -c 27 | od -t x1 -A n |
  tr -s -c 0-9 ' ' |
  grep -q '01 01 00 01 02 00 01 03 01 01 02 00 01 03 00 01 01 02 01 03 00 01 01 00 01 02 03'
